name: Linux

on:
  workflow_dispatch: # for manual workflow trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux_cpp11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 4.8
          platform: x64

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
          cmake --build .
        env:
          CC: gcc-4
          CXX: g++-4

      - name: Test
        run: cd build && ./closure_test

  linux_cpp14:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
          cmake --build . 

      - name: Test
        run: cd build && ./closure_test

  linux_cpp17:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
          cmake --build .

      - name: Test
        run: cd build && ./closure_test
